Update wso2-intg-test-2-node-cfn.yaml

diff --git a/jobs/intg-test-resources/wso2-intg-test-2-node-cfn.yaml b/jobs/intg-test-resources/wso2-intg-test-2-node-cfn.yaml
--- a/jobs/intg-test-resources/wso2-intg-test-2-node-cfn.yaml
+++ b/jobs/intg-test-resources/wso2-intg-test-2-node-cfn.yaml
@@ -253,6 +253,11 @@ Resources:
     Type: 'AWS::EC2::RouteTable'
     Properties:
       VpcId: !Ref WSO2EnvVPC
+  WSO2EnvBastionEIPAssociation:
+    Type: 'AWS::EC2::EIPAssociation'
+    Properties:
+      AllocationId: !GetAtt WSO2EnvBastionEIP.AllocationId
+      InstanceId: !Ref WSO2EnvBastionInstance
 
   ################################
   # Create network configurations
@@ -493,6 +498,10 @@ Resources:
     Type: 'AWS::EC2::EIP'
     Properties:
       Domain: vpc
+  WSO2EnvBastionEIP:
+    Type: 'AWS::EC2::EIP'
+    Properties:
+      Domain: vpc
 
 #Other
   WSO2UnixInstance1:
@@ -554,7 +563,10 @@ Resources:
           setup_java_env
           source /etc/environment
           cat /dev/null > ~/.bash_history && history -c
+          echo 'point0' > /opt/testgrid/agent/debug.log
+          echo '${CustomUserData}' >> /opt/testgrid/agent/debug.log
           ${CustomUserData}
+          echo 'point1' >> /opt/testgrid/agent/debug.log
 
           #Create a file with testplan properties & write outputs
           echo "LBHost=${WSO2EnvApplicationLoadBalancer.DNSName}" >> testplan.properties
@@ -658,7 +670,10 @@ Resources:
                 setup_java_env
                 source /etc/environment
                 cat /dev/null > ~/.bash_history && history -c
+                echo 'point1' > /opt/testgrid/agent/debug.log
+                echo '${CustomUserData}' >> /opt/testgrid/agent/debug.log
                 ${CustomUserData}
+                echo 'point1' >> /opt/testgrid/agent/debug.log
 
                 #Create a file with testplan properties & write outputs
                 echo "LBHost=${WSO2EnvApplicationLoadBalancer.DNSName}" >> testplan.properties
@@ -768,6 +783,67 @@ Resources:
           PrivateIpAddress: 10.0.1.110
           GroupSet:
             - !Ref WSO2EnvInstanceSecurityGroup
+  WSO2EnvBastionInstance:
+    Type: 'AWS::EC2::Instance'
+    Properties:
+      DisableApiTermination: 'false'
+      InstanceInitiatedShutdownBehavior: stop
+      ImageId: !Ref AMI
+      InstanceType: t2.micro
+      KeyName: !Ref EC2KeyPair
+      Monitoring: 'false'
+      UserData: !Base64
+        'Fn::Sub': |
+                #cloud-boothook
+                #!/bin/bash
+                set -e
+                set -o xtrace
+
+                setup_java_env() {
+                source /etc/environment
+                echo JDK_PARAM=${JDK} >> /opt/wso2/java.txt
+                REQUESTED_JDK_PRESENT=$(grep "^${JDK}=" /etc/environment | wc -l)
+                if [ $REQUESTED_JDK_PRESENT = 0 ]; then
+                printf "The requested JDK, ${JDK}, not found in /etc/environment: \n $(cat /etc/environment)."
+                exit 1; // todo: inform via cfn-signal
+                fi
+                  JAVA_HOME=$(grep "^${JDK}=" /etc/environment | head -1 | sed "s:${JDK}=\(.*\):\1:g" | sed 's:"::g')
+
+                 echo ">> Setting up JAVA_HOME ..."
+                  JAVA_HOME_EXISTS=$(grep -r "JAVA_HOME=" /etc/environment | wc -l  )
+                  if [ $JAVA_HOME_EXISTS = 0 ]; then
+                    echo ">> Adding JAVA_HOME entry."
+                    echo JAVA_HOME=$JAVA_HOME >> /etc/environment
+                  else
+                    echo ">> Updating JAVA_HOME entry."
+                    sed -i "/JAVA_HOME=/c\JAVA_HOME=$JAVA_HOME" /etc/environment
+                fi
+                  source /etc/environment
+                  echo "export JAVA_HOME=$JAVA_HOME" >> /etc/profile
+                            source /etc/profile
+                  }
+
+                mkdir -p /opt/wso2/workspace
+                #TODO: We need to figure out the default user in the system.
+                #So, provided permissions to all the users. Need to fix!
+                chmod 777 -R /opt/wso2/workspace
+                cd /opt/wso2/workspace
+
+                setup_java_env
+                source /etc/environment
+                cat /dev/null > ~/.bash_history && history -c
+                echo 'point0' > /opt/testgrid/agent/debug.log
+                echo '${CustomUserData}' >> /opt/testgrid/agent/debug.log
+                ${CustomUserData}
+                echo 'point1' >> /opt/testgrid/agent/debug.log
+                /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource WSO2UnixInstance2 --region ${AWS::Region}
+      NetworkInterfaces:
+        - DeleteOnTermination: 'true'
+          Description: Primary network interface
+          DeviceIndex: 0
+          SubnetId: !Ref WSO2EnvPublicSubnet1
+          GroupSet:
+            - !Ref WSO2EnvInstanceSecurityGroup    
   #######################
   # Create RDS instances
   #######################
@@ -992,6 +1068,9 @@ Outputs:
     Value: !If [IsUnix, !Ref WSO2UnixInstance1, !If [IsWindows, !Ref WSO2WindowsInstance1, !Ref 'AWS::NoValue']]
   WSO2Node2ID:
     Value: !If [IsUnix, !Ref WSO2UnixInstance2, !If [IsWindows, !Ref WSO2WindowsInstance2, !Ref 'AWS::NoValue']]
+  BastianEIP:
+    Value: !Sub '${WSO2EnvBastionInstance.PublicIp}'
+    Description: Elastic IP of the Bastion Instance
   ProductGITURL:
     Value: !Ref ProductGITURL
     Description: URL of the product GIT repo
